dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += \
		imx8m-var-dart-sd-emmc-dual-display.dtb \
		imx8m-var-dart-emmc-wifi-dual-display.dtb

always          := $(dtb-y)
subdir-y        := $(dts-dirs)
clean-files     := *.dtb

